name: Release PortalBox
on:
  push:
    tags:
      - "v*"
concurrency:
  group: release
  cancel-in-progress: true
jobs:
  build:
    strategy:
      matrix:
        os: [windows-2019, ubuntu-20.04, macos-11]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: 1.60.0
            override: true
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --locked
      - name: Build release binary for ${{ matrix.os }}
        uses: actions-rs/cargo@v1
        with:
          command: xtask
          args: dist
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: portalbox-*.tar.gz
